language: node_js

node_js:
  - '7.2'

cache: yarn
install: yarn
script: yarn run build

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET

